const auditFields = [
  {
    id: 1,
    name: "Study Data",
    fName: "Study Title",
    fControlName: "studyTitle",
  },
  {
    id: 1,
    name: "Study Data",
    fName: "Project No",
    fControlName: "projectNo",
  },
  {
    id: 1,
    name: "Study Data",
    fName: "Study Date",
    fControlName: "studyDate",
  },
  {
    id: 1,
    name: "Study Data",
    fName: "Site ID / Name",
    fControlName: "siteId",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Subject ID",
    fControlName: "subjectId",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Subject Counter",
    fControlName: "subjectCounter",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Year of Birth (if available)",
    fControlName: "subjectYear",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Unknown",
    fControlName: "subjectUnknown",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Gender",
    fControlName: "subjectGender",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Gender",
    fControlName: "subjectGender",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Ethnicity",
    fControlName: "otherCheck",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Ethnicity",
    fControlName: "otherCheck",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Ethnicity Other check",
    fControlName: "subjectOtherText",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Place of birth City",
    fControlName: "placeOfBirthCity",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Place of birth State",
    fControlName: "placeOfBirthState",
  },
  {
    id: 2,
    name: "Subject Data",
    fName: "Residence City",
    fControlName: "residencyCity",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Date of HCC Diagnosis",
    fControlName: "dateOfHcc",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Date of HCC Diagnosis Unknown",
    fControlName: "baseLineIfDateRadio",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Date of HCC Diagnosis Year",
    fControlName: "baseLineIfDate",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Age at HCC Diagnosis",
    fControlName: "baseLineAgeOfHcc",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Height",
    fControlName: "baseLineHeight",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Weight",
    fControlName: "weightHggBaseLine",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Type of Insurance",
    fControlName: "insuranceValue",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Type of Insurance",
    fControlName: "insuranceValue",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Type of Insurance",
    fControlName: "insuranceValue",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Type of Insurance Other",
    fControlName: "insuraceValueOtherBaseline",
  },
  {
    id: 3,
    name: "Baseline Characteristics",
    fName: "Insurance Details",
    fControlName: "insuraceDetailsBaseLine",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Hemoglobin A1C (HbA1c) From",
    fControlName: "hemoGlobinFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Hemoglobin A1C (HbA1c) To",
    fControlName: "hemoGlobinTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Hemoglobin A1C (HbA1c) Value",
    fControlName: "hemoGlobinValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Hemoglobin A1C (HbA1c) Unknown",
    fControlName: "hemoGlobinUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Alanine Aminotransferase(ALT) From",
    fControlName: "alanineFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Alanine Aminotransferase(ALT) To",
    fControlName: "alanineTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Alanine Aminotransferase(ALT) Value",
    fControlName: "alanineValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Alanine Aminotransferase(ALT) Unknown",
    fControlName: "alanineUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "AST From",
    fControlName: "aspartateFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "AST To",
    fControlName: "aspartateTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "AST Value",
    fControlName: "aspartateValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "AST Unknown",
    fControlName: "aspartateUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Total Bilirubin From",
    fControlName: "bilirubinFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Total Bilirubin TO",
    fControlName: "bilirubinTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Total Bilirubin Value",
    fControlName: "bilirubinValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Total Bilirubin Unknown",
    fControlName: "bilirubinUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "ALP From",
    fControlName: "alkalineFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "ALP To",
    fControlName: "alkalineTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "ALP Value",
    fControlName: "alkalineValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "ALP Unknown",
    fControlName: "alkalineUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Albumin To",
    fControlName: "albuminTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Albumin Value",
    fControlName: "albuminValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Albumin Unknown",
    fControlName: "albuminUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Platelets From",
    fControlName: "platelatesFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Platelets To",
    fControlName: "platelatesTo",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Platelets Value",
    fControlName: "platelatesValue",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Platelets Unknown",
    fControlName: "platelatesUnknown",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Creatinine From",
    fControlName: "creatinineFrom",
  },
  {
    id: 4,
    name: "Laboratory Parameters",
    fName: "Creatinine To",
    fControlName: "creatinineTo",
  },
];
