module.exports = {
  INIT: "INIT",
  SUBMITTED_TO_REVIEWER_FROM_DATAENTRY: "SUBMITTED_TO_REVIEWER_FROM_DATAENTRY",
  INPROGRESS_AT_DATAENTRY_FROM_REVIEWER_SUBMISSION:
    "INPROGRESS_AT_DATAENTRY_FROM_REVIEWER_SUBMISSION",
  INPROGRESS_AT_DATAENTRY_FROM_REVIEWER_RESUBMISSION:
    "INPROGRESS_AT_DATAENTRY_FROM_REVIEWER_RESUBMISSION",
  RESUBMITTED_TO_REVIEWER_FROM_DATAENTRY:
    "RESUBMITTED_TO_REVIEWER_FROM_DATAENTRY",
  INPROGRESS_AT_REVIEWER_FROM_DATAENTRY_SUBMISSION:
    "INPROGRESS_AT_REVIEWER_FROM_DATAENTRY_SUBMISSION",
  INPROGRESS_AT_REVIEWER_FROM_PI_SUBMISSION:
    "INPROGRESS_AT_REVIEWER_FROM_PI_SUBMISSION",
  INPROGRESS_AT_REVIEWER_FROM_DATAENTRY_RESUBMISSION:
    "INPROGRESS_AT_REVIEWER_FROM_DATAENTRY_RESUBMISSION",
  INPROGRESS_AT_REVIEWER_FROM_PI_RESUBMISSION:
    "INPROGRESS_AT_REVIEWER_FROM_PI_RESUBMISSION",
  SUBMITTED_TO_DATAENTRY_FROM_REVIEWER: "SUBMITTED_TO_DATAENTRY_FROM_REVIEWER",
  RESUBMITTED_TO_DATAENTRY_FROM_REVIEWER:
    "RESUBMITTED_TO_DATAENTRY_FROM_REVIEWER",
  SUBMITTED_TO_PI: "SUBMITTED_TO_PI",
  RESUBMITTED_TO_PI: "RESUBMITTED_TO_PI",
  INPROGRESS_AT_PI_SUBMISSION: "INPROGRESS_AT_PI_SUBMISSION",
  INPROGRESS_AT_PI_RESUBMISSION: "INPROGRESS_AT_PI_RESUBMISSION",
  SUBMITTED_TO_REVIWER_FROM_PI: "SUBMITTED_TO_REVIWER_FROM_PI",
  RESUBMITTED_TO_REVIWER_FROM_PI: "RESUBMITTED_TO_REVIWER_FROM_PI",
  SIGN_OFF: "SIGN_OFF",
};
